version: "3"

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore-producao
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: estudos-nerdstore-sql-server:latest
    container_name: estudos-nerdstore-sql-server
    build: 
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1444:1433"  
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"


  web-mvc:
    image: estudos-nerdstore-web-mvc-ecommerce:latest
    container_name: estudos-nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/Estudos.NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - api-catalogo


  api-catalogo: 
    image: estudos-nerdstore-api-catalogo:latest
    container_name: estudos-nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/Estudos.NSE.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301
    depends_on:
      - rabbitmq