version: "3"

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore-producao
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: estudos-nerdstore-sql-server:latest
    container_name: estudos-nerdstore-sql-server
    build: 
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1444:1433"  
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  web-mvc:
    image: estudos-nerdstore-web-mvc-ecommerce:latest
    container_name: estudos-nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/Estudos.NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
    restart: always  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    volumes: 
      - dpkeys:/var/data_protection_keys/  
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras

  api-identidade:
    image: estudos-nerdstore-api-identidade:latest
    container_name: estudos-nerdstore-api-identidade    
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Identidade.API/Dockerfile
    restart: always    
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5101;http://+5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server

  api-carrinho:
    image: estudos-nerdstore-api-carrinho:latest
    container_name: estudos-nerdstore-api-carrinho
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Carrinho.API/Dockerfile
    restart: always        
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5201;http://+5202
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server 
        
  api-catalogo:
    image: estudos-nerdstore-api-catalogo:latest
    container_name: estudos-nerdstore-api-catalogo
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Catalogo.API/Dockerfile
    restart: always  
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5301;http://+5302
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server

  api-cliente:
    image: estudos-nerdstore-api-cliente:latest
    container_name: estudos-nerdstore-api-cliente    
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Cliente.API/Dockerfile
    restart: always  
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5401;http://+5402
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server  

  api-bff-compras:
    image: estudos-nerdstore-api-bff-compras:latest
    container_name: estudos-nerdstore-api-bff-compras
    build: 
      context: ../src
      dockerfile: ./api gateways/Estudos.NSE.Bff.Compras/Dockerfile
    restart: always  
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5501;http://+5502
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido
            
  api-pagamento:
    image: estudos-nerdstore-api-pagamento:latest
    container_name: estudos-nerdstore-api-pagamento    
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Pagamento.API/Dockerfile
    restart: always  
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5601;http://+5602
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - api-pedido
      - sql-server
            
  api-pedido:
    image: estudos-nerdstore-api-pedido:latest
    container_name: estudos-nerdstore-api-pedido    
    build: 
      context: ../src
      dockerfile: ./services/Estudos.NSE.Pedido.API/Dockerfile
    restart: always   
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5701;http://+5702
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  estudos-nerdstore-server:
    image: estudos-nerdstore-server:latest
    container_name: estudos-nerdstore-server    
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always   
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc

volumes:
    dpkeys:            