version: "3"

services:

  web-mvc:
    image: estudos-nerdstore-web-mvc-ecommerce:latest
    container_name: estudos-nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/Estudos.NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
